server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.49.0:3306/single_blog?serveTimezone=GMT
    username: root
    password: swt620523
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
    host: 39.106.49.0
    password: swt620523
  rabbitmq:
    host: 39.106.49.0
    password: swt620523
    username: admin
    port: 5672
  application:
    name: single-blog

groot:
  swagger:
    base-package: com.blog
  rabbit-mq:
    exchange-name: single-blog
    queue-name: single-blog
    routing-key: single-blog
  login:
    # redis中用户token过期时间（min）
    expire-time: 30
  file:
    # 文件根目录
    root-path: E://files