server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/single_blog?serveTimezone=GMT
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    password: 123456
  rabbitmq:
    host: localhost
    password: 123456
    username: admin
    port: 5672
  application:
    name: groot-base-single-service

groot:
  # 登录拦截器是否开启
  login-interceptor: true
  swagger:
    base-package: com.groot.base
  rabbit-mq:
    exchange-name: groot-base-single-service
    queue-name: groot-base-single-service
    routing-key: groot-base-single-service
  login:
    # redis中用户token过期时间（min）
    expire-time: 30
  file:
    # 文件根目录
    root-path: E://files